# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88da7fecaf0d99b57064f66efe49f247a129d5754d906eb326c1eb9f316d3ffcb9249ffeb326f45784606fe033e310c09744e507b02ed2fc341f9d2bbacc987c

test:
  secret_key_base: 7b0ca805d041a295c31f847521fc2d581a97a3bfaa01990fa7829cef48be016efa18d5fdc95263b46bf4970c198fd8566226afa542314c5dfb88d134ac477d4b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
